#!/bin/bash

set -e

# Github SSH key
ssh-keygen -t rsa -b 4096 -C "YOUR-GITHUB-EMAIL"
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa

ln -fsn ~/dotfiles/.gitignore_global ~/.gitignore_global

git config --global core.editor vim
git config --global core.excludesfile ~/.gitignore_global
git config --global push.default current
git config --global user.email "YOUR-GITHUB-EMAIL"
git config --global user.name $(whoami)


# Development tools
sudo pacman -S atom calibre dbeaver docker docker-compose eslint
sudo pacman -S firefox firefox-developer-edition flameshot
sudo pacman -S heroku-cli hunspell hunspell-en_GB hyper keepassxc keychain latte
sudo pacman -S mysql-clients nodejs-emojione nginx ngrok oh-my-zsh peek pencil slack
sudo pacman -S tig tmux typescript visual-studio-code-bin watchman yarn
sudo pacman -S zsh zsh-autosuggestions zsh-syntax-highlighting


# Dotfiles
git clone git@github.com:Willibaur/dotfiles.git ~


# Zsh
chsh -s `which zsh`
rm -rf  ~/.zshrc
ln -fsn ~/dotfiles/zsh/.zshrc ~/.zshrc


# Antigen
curl -L git.io/antigen > ~/antigen.zsh
source ~/.zshrc


# Asdf
git clone https://github.com/asdf-vm/asdf ~/.asdf

ln -fsn ~/dotfiles/asdf/.asdfrc ~/.asdfrc
ln -fsn ~/dotfiles/asdf/.default-gems ~/.default-gems

asdf plugin-add ruby
asdf plugin-add nodejs
bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring


# Docker
sudo groupadd docker
sudo gpasswd -a $(whoami) docker
newgrp docker

docker ps
systemctl enable docker
systemctl start docker
systemctl status docker
docker ps


# Default directories
mkdir ~/container-volumes ~/open-source ~/side-projects ~/study ~/work


# MySql
pacman -S mysql-clients
docker run -d --name mysql -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -v $HOME/container-volumes/mysql/datadir:/var/lib/mysql mysql:5.6


# PostgreSql
docker run -d --name postgres -p 5432:5432 -v $HOME/container-volumes/postgres:/var/lib/postgresql/data postgres:11.0


# Redis
docker run -d --name redis -p 6379:6379 redis


# Settings for HyperJS
touch ~/.hyper_plugins/.hyper-sync-settings.json
echo "{
  "gistId": "",
  "personalAccessToken" : ""
}" > .hyper-sync-settings.json
ln -fsn ~/dotfiles/hyperjs/.hyper.js ~/.hyper.js
ln -fsn ~/dotfiles/hyperjs/package.json ~/.hyper_plugins/package.json
ln -fsn ~/dotfiles/hyperjs/node_modules ~/.hyper_plugins/node_modules
ln -fsn ~/dotfiles/hyperjs/yarn.lock ~/.hyper_plugins/yarn.lock


# Yay => AUR Package manager if pacman is not available
git clone https://aur.archlinux.org/yay.git ~/.yay
cd .yay
makepkg -si
cd ~


# Gnome
sudo systemctl disable lightdm
sudo pacman -S gdm
sudo systemctl enable gdm
sudo pacman -Rsn lightdm

ln -fsn ~/dotfiles/gnome/gnome_shell_extensions_appfolder.txt ~/gnome_shell_extensions_appfolder.txt
ln -fsn ~/dotfiles/gnome/gnome_shell_extensions_conf.txt ~/gnome_shell_extensions_conf.txt
ln -fsn ~/dotfiles/gnome/gnome_shell_extensions_id.txt ~/gnome_shell_extensions_id.txt
ln -fsn ~/dotfiles/gnome/gtk.css ~/.config/gtk-3.0/gtk.css


# Tmux
ln -fsn ~/dotfiles/.tmux.conf  ~/.tmux.conf
ln -fsn ~/dotfiles/tmuxinator ~/.tmuxinator
