#!/bin/bash

set -e

# Dotfiles
cd ~

# Development tools
pacman -S calibre dbeaver docker docker-compose dropbox eslint
pacman -S firefox firefox-developer-edition flameshot font-manager
pacman -S heroku-cli hyper keepassxc mysql-clients nodejs-emojione
pacman -S nginx ngrok oh-my-zsh peek pencil slack tig tmux
pacman -S typescript visual-studio-code-bin yarn zsh zsh-autosuggestions zsh-syntax-highlighting


# Keyring
ssh-keygen -t rsa -b 4096 -C "YOUR-GITHUB-EMAIL"
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa


# Yay => AUR Package manager if pacman is not available
git clone https://aur.archlinux.org/yay.git ~/.yay
cd .yay
makepkg -si
cd ~


# Gnome
sudo systemctl disable lightdm
sudo pacman -S gdm
sudo systemctl enable gdm
sudo pacman -Rsn lightdm


# Settings for HyperJS
touch ~/.hyper_plugins/.hyper-sync-settings.json
echo "{
  "gistId": "",
  "personalAccessToken" : ""
}" > .hyper-sync-settings.json
ln -fsn ~/dotfiles/hyperjs/.hyper.js ~/.hyper.js
ln -fsn ~/dotfiles/hyperjs/package.json ~/.hyper_plugins/package.json



# Git
# $1 => github email

git clone git@github.com:Willibaur/dotfiles.git

ln -fsn ~/dotfiles/.gitignore_global ~/.gitignore_global

git config --global core.editor vim
git config --global core.excludesfile ~/.gitignore_global
git config --global push.default current
git config --global user.email "$1"
git config --global user.name $(whoami)

ln -fsn ~/dotfiles/gnome/gnome_shell_extensions_appfolder.txt ~/gnome_shell_extensions_appfolder.txt
ln -fsn ~/dotfiles/gnome/gnome_shell_extensions_conf.txt ~/gnome_shell_extensions_conf.txt
ln -fsn ~/dotfiles/gnome/gnome_shell_extensions_id.txt ~/gnome_shell_extensions_id.txt
ln -fsn ~/dotfiles/gnome/gtk.css ~/.config/gtk-3.0/gtk.css


# Zsh
chsh -s `which zsh`
rm -rf  ~/.zshrc
ln -fsn ~/dotfiles/zsh/.zshrc ~/.zshrc


# Tmux
ln -fsn ~/dotfiles/.tmux.conf  ~/.tmux.conf
ln -fsn ~/dotfiles/tmuxinator ~/.tmuxinator


# Antigen
curl -L git.io/antigen > ~/antigen.zsh
source ~/.zshrc


# Asdf
git clone https://github.com/asdf-vm/asdf ~/.asdf

ln -fsn ~/dotfiles/asdf/.asdfrc ~/.asdfrc
ln -fsn ~/dotfiles/asdf/.default-gems ~/.default-gems

asdf plugin-add ruby
asdf plugin-add nodejs
bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring

# install rubygems
gem update --system

ELIXIR_VERSION=
ERLANG_VERSION=22.0.1
NODE_VERSION=10.15.0
RUBY_VERSION=2.6.3

asdf install ruby $RUBY_VERSION
asdf global ruby $RUBY_VERSION

asdf install nodejs $NODE_VERSION
asdf global nodejs $NODE_VERSION

asdf install erlang $ERLANG_VERSION
asdf global erlang $ERLANG_VERSION

asdf install elixir $ELIXIR_VERSION
asdf global elixir $ELIXIR_VERSION


# Docker
sudo groupadd docker
sudo gpasswd -a $(whoami) docker
newgrp docker

docker ps
systemctl enable docker
systemctl start docker
systemctl status docker
docker ps

# Container for saving data
mkdir ~/container-volumes ~/open-source ~/side-projects  ~/study

# MySql
pacman -S mysql-clients
docker run -d --name mysql -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -v $HOME/container-volumes/mysql/datadir:/var/lib/mysql mysql:5.6

# PostgreSql
docker run -d --name postgres -p 5432:5432 -v $HOME/container-volumes/postgres:/var/lib/postgresql/data postgres:11.0

# Redis
docker run -d --name redis -p 6379:6379 redis
