#!/bin/bash

set -e

# Dotfiles
cd ~

# Development tools
pacman -S calibre dbeaver docker docker-compose dropbox firefox firefox-developer-edition eslint flameshot
pacman -S heroku-cli keepassxc mysql-clients
pacman -S nginx ngrok oh-my-zsh peek pencil slack tig
pacman -S tmux vim visual-studio-code-bin yarn zsh zsh-autosuggestions zsh-syntax-highlighting


# Yay => AUR Package manager if pacman is not available
git clone https://aur.archlinux.org/yay.git ~/.yay
cd .yay
makepkg -si
cd ~


# Gnome
sudo systemctl disable lightdm
sudo pacman -S gdm
sudo systemctl enable gdm
sudo pacman -Rsn lightdm

ln -fsn ~/dotfiles/gnome/gnome_shell_extensions_appfolder.txt ~/gnome_shell_extensions_appfolder.txt
ln -fsn ~/dotfiles/gnome/gnome_shell_extensions_conf.txt ~/gnome_shell_extensions_conf.txt
ln -fsn ~/dotfiles/gnome/gnome_shell_extensions_id.txt ~/gnome_shell_extensions_id.txt
ln -fsn ~/dotfiles/gnome/gtk.css ~/.config/gtk-3.0/gtk.css


# Keyring
ssh-keygen -t rsa -b 4096 -C "$1"
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa


# Zsh
chsh -s `which zsh`
rm -rf  ~/.zshrc
ln -fsn ~/dotfiles/zsh/.zshrc ~/.zshrc


# Antigen
yay -S antigen-git
source ~/.zshrc


# Git
# $1 => github email
ln -fsn ~/dotfiles/.gitignore_global ~/.gitignore_global

git config --global core.editor vim
git config --global core.excludesfile ~/.gitignore_global
git config --global push.default current
git config --global user.email "$1"
git config --global user.name "$USERNAME"


# Asdf
git clone https://github.com/asdf-vm/asdf ~/.asdf

ln -fsn ~/dotfiles/asdf/.asdfrc ~/.asdfrc
ln -fsn ~/dotfiles/asdf/.default-gems ~/.default-gems

asdf plugin-add ruby
asdf plugin-add nodejs
zsh ~/.asdf/plugins/nodejs/bin/import-release-team-keyring

RUBY_VERSION=2.5.1
NODE_VERSION=8.11.4

asdf install ruby $RUBY_VERSION
asdf global ruby $RUBY_VERSION

asdf install nodejs $NODE_VERSION
asdf global nodejs $NODE_VERSION


# Tmux
ln -fsn ~/dotfiles/.tmux.conf  ~/.tmux.conf
ln -fsn ~/dotfiles/tmuxinator ~/.tmuxinator


# Docker
sudo groupadd docker
sudo gpasswd -a $USERNAME docker
newgrp docker

docker ps
systemctl enable docker
systemctl start docker
systemctl status docker
docker ps

# Container for saving data
mkdir ~/container-volumes

# MySql
pacman -S mysql-clients
docker run -d --name mysql -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -v $HOME/container-volumes/mysql/datadir:/var/lib/mysql mysql:5.6

# PostgreSql
docker run -d --name postgres -p 5432:5432 -v $HOME/container-volumes/postgres:/var/lib/postgresql/data postgres:11.0

# Redis
docker run -d --name redis -p 6379:6379 redis
